// CAM UI strings. `en` is the reference shape; `de` must provide every key (enforced by the Strings type).
export const camStrings = {
  en: {
    appTitle: 'Makerspace CAM',
    // ribbon tabs
    tabFile: 'File', tabLayout: 'Layout', tabOps: 'Operations', tabMachine: 'Machine', tabView: 'View',
    // file
    newProject: 'New', open: 'Open', saveFile: 'Save', saveAs: 'Save as…', importDrawing: 'Import DXF/SVG', exportGcode: 'Export G-code', options: 'Options', recent: 'Recent',
    // layout
    move: 'Move', rotate90: 'Rotate 90°', rotateCcw: 'Rotate −90°', mirrorX: 'Mirror X', mirrorY: 'Mirror Y', array: 'Array', group: 'Group', ungroup: 'Ungroup', duplicate: 'Duplicate', deleteSel: 'Delete', addText: 'Text', addPoint: 'Drill point', zeroPoint: 'Zero point', sheet: 'Sheet', fit: 'Fit view', center: 'Center on sheet',
    // ops
    contourOutside: 'Contour outside', contourInside: 'Contour inside', contourOn: 'Contour on line', cutout: 'Cutout', pocket: 'Pocket', engrave: 'Engrave', drill: 'Drill', thread: 'Thread', laserCut: 'Laser cut', laserEngrave: 'Laser engrave', activeTool: 'Active tool', noTool: 'no tool', selectFirst: 'Select one or more outlines first.',
    // machine
    machine: 'Machine', postProcessor: 'Post-processor', generate: 'Generate G-code', simulate: 'Simulate', estTime: 'Est. time',
    // view
    grid: 'Grid', snap: 'Snap', showMilling: 'Milling', showToolpaths: 'Tool paths', showRapids: 'Rapids', layers: 'Layers', view2d: '2D Layout', view3d: '3D Preview', viewGcode: 'G-Code', language: 'Language', darkMode: 'Dark mode',
    // tree
    tree: 'Project', tools: 'Tools', unassigned: 'Unassigned objects', groups: 'Groups', operations: 'Operations', objects: 'Objects', noObjects: 'No objects yet. Import a DXF or SVG file.', instances: (n: number) => `× ${n}`,
    // params panel
    params: 'Properties', nothingSelected: 'Nothing selected', placement: 'Placement', name: 'Name', posX: 'X', posY: 'Y', rotation: 'Rotation', scale: 'Scale', mirrored: 'Mirrored', arrayNx: 'Columns', arrayNy: 'Rows', arrayDx: 'Spacing X', arrayDy: 'Spacing Y', paths: 'Paths', closedPaths: 'closed', openPaths: 'open', size: 'Size', layer: 'Layer', locked: 'Locked',
    stock: 'Stock / sheet', width: 'Width', height: 'Height', thickness: 'Thickness', material: 'Material', safeZ: 'Safe Z', clearZ: 'Clearance Z', zZero: 'Z zero', zTop: 'Stock top', zBottom: 'Machine bed', originMode: 'Zero point', origin: { manual: 'Manual', 'sheet-corner': 'Sheet corner', 'sheet-center': 'Sheet centre', 'parts-bbox-corner': 'Parts bounding box corner', 'parts-bbox-center': 'Parts bounding box centre' } as Record<string, string>, corner: 'Corner', corners: { bl: 'bottom left', br: 'bottom right', tl: 'top left', tr: 'top right' } as Record<string, string>,
    materials: { mdf: 'MDF', osb: 'OSB', plywood: 'Plywood (multiplex)', wood: 'Solid wood', aluminium: 'Aluminium', acrylic: 'Acrylic', generic: 'Generic' } as Record<string, string>,
    operation: 'Operation', opType: 'Type', tool: 'Tool', depth: 'Depth', stepDown: 'Step-down', side: 'Side', sides: { outside: 'outside', inside: 'inside', on: 'on the line', left: 'left', right: 'right' } as Record<string, string>, entry: 'Entry', entries: { plunge: 'plunge', ramp: 'ramp', helix: 'helix' } as Record<string, string>, rampAngle: 'Ramp angle', climb: 'Climb milling', startT: 'Start position', startAngle: 'Start angle', zOffset: 'Start depth', zOffsetHint: 'Depth below the surface where cutting starts (e.g. 2 after planing 2 mm); the operation cuts from start depth to start depth + depth.', feedOverride: 'Feed (override)', plungeOverride: 'Plunge feed (override)', enabled: 'Enabled', targets: 'Targets', tabs: 'Bridges (tabs)', tabCount: 'Count', tabWidth: 'Width', tabHeight: 'Height', overcut: 'Corner overcut', overcuts: { none: 'none', dogbone: 'dog-bone', tbone: 'T-bone' } as Record<string, string>, strategy: 'Strategy', strategies: { offset: 'offset (contour parallel)', raster: 'raster (linear, lift between lines)', zigzag: 'zig-zag (across, step over, back)' } as Record<string, string>, rasterAngle: 'Raster angle', stepOver: 'Step-over', pocketSide: 'Wall pass', pocketSides: { inside: 'inside the contour', on: 'on the contour', outside: 'outside the contour (+ safe zone)' } as Record<string, string>, outsideWidth: 'Material removed around the contour', widthUnits: { mm: 'mm', tool: 'tool widths' } as Record<string, string>, outsideWidthHint: 'Material removed outside the contour (safe zone for other tools); the interior is always cleared as well.', pocketHint: 'The wall pass runs first, then the whole interior is cleared with the step-over. Exclusion contours stay standing (plus their margin).', roleCut: 'Area to clear', roleExclude: 'Exclusion (stays)', margin: 'Margin around', addSelection: 'Add selected contours', addSelectionExclude: 'Add selection as exclusion', tabMode: 'Placement', tabModes: { auto: 'automatic (opposite straight sides first)', manual: 'manual (click in the 2D view)' } as Record<string, string>, placeTabs: 'Place bridges in 2D view', placingTabs: 'Placing bridges… click the contour to add, click a bridge to remove', stopPlacing: 'Done', tabsPlaced: (n: number) => `${n} placed`, placePoints: 'Place points in 2D view', placingPoints: 'Placing points… click a snap point (line centre, ⅓ ⅔ ¼ ¾, contour centre) to add, click a point to remove. Hover a point briefly to pin it as a reference; two references span a dotted line with its own snap points. Esc clears.', pointsPlaced: (n: number) => `${n} points`, pointAt: (x: number, y: number) => `Point (${x.toFixed(2)}, ${y.toFixed(2)})`, reference: 'Reference', snapHintTabs: 'Snap points (line centre, ⅓ ⅔ ¼ ¾) are highlighted while placing.',
    depthThrough: 'through (thickness + 1 mm)',
    // tool editor
    toolLibrary: 'Tool library', machines: 'Machines', posts: 'Post-processors', addTool: 'Add tool', addMachine: 'Add machine', toolKind: 'Kind', toolKinds: { endmill: 'End mill', facemill: 'Face / surfacing mill', ballnose: 'Ball nose', vbit: 'V-bit', drill: 'Drill', saw: 'Saw blade', laser: 'Laser' } as Record<string, string>, fluteLength: 'Cutting length', surface: 'Surface (plane sheet)', surfaceHint: 'Planes the whole sheet with the active tool from the start depth down by the given depth.', slot: 'Tool number (T)', diameter: 'Diameter', flutes: 'Flutes', tipAngle: 'Tip angle', spindleSpeed: 'Spindle speed', feed: 'Feed', plungeFeed: 'Plunge feed', stepOverPct: 'Step-over (% of Ø)', assistant: 'Cutting-data assistant', applyToTool: 'Apply to tool', close: 'Close', save: 'Save', cancel: 'Cancel', delete: 'Delete', confirmDelete: (n: string) => `Delete "${n}"?`, duplicateItem: 'Duplicate',
    machineName: 'Name', machineKind: 'Type', kinds: { cnc: 'CNC router / mill', laser: 'Laser' } as Record<string, string>, travelX: 'Travel X', travelY: 'Travel Y', travelZ: 'Travel Z', nMax: 'Max. spindle speed', nMin: 'Min. spindle speed', feedMaxXy: 'Max. feed XY', feedMaxZ: 'Max. feed Z', rapidXy: 'Rapid XY', rapidZ: 'Rapid Z', toolChange: 'Tool change', toolChanges: { manual: 'manual', auto: 'automatic' } as Record<string, string>, climbAllowed: 'Climb milling allowed', climbNotAllowed: 'Climb milling is not allowed on this machine; conventional milling is used.', info: 'Notes', importPp: 'Import Estlcam .pp', exportPp: 'Export .pp', builtIn: 'built-in',
    // gcode view
    gcodeEmpty: 'No operations yet. Select outlines and add an operation from the Operations tab.', preparing3d: 'Preparing 3D preview…', building3dGrid: 'Building the surface grid', simulating3d: (pct: number) => `Simulating material removal · ${pct} %`, loading3d: 'Loading 3D preview…', lines: (n: number) => `${n} lines`, download: 'Download', copy: 'Copy', copied: 'Copied',
    // g-code disclaimer (export dialog, g-code view banner, file header)
    gcodeWarnTitle: 'Custom G-code generator — use at your own risk',
    gcodeWarnBanner: 'This is a custom G-code generator. The output is used at your own risk — watch the machine and hit the emergency stop at the first sign of a problem.',
    gcodeWarnLead: 'This program is a custom G-code generator. G-code is not really standardised, and no software is bug free — parts of the output have been checked, but correctness for your machine and your job cannot be guaranteed.',
    gcodeWarnPoints: [
      'You use the generated G-code entirely at your own risk.',
      'Check the program (and the 2D/3D preview) before running it.',
      'Never leave the machine unattended — keep it in view the whole time.',
      'Keep your hand at the emergency stop (not the pause) and hit it as soon as anything looks wrong.',
      'Run a dry run above the material or with reduced feed if you are unsure.',
    ] as string[],
    gcodeWarnAck: 'I understand — export',
    // g-code explainer
    srcProgram: 'Generated program', srcCustom: 'Own G-code', pastePlaceholder: 'Paste G-code here…', pasteEmpty: 'Paste a G-code program above and every line is explained for the selected machine.',
    explainFor: 'Explained for', explainSelect: 'Select a line to see the details.', explainLine: (n: number) => `Line ${n}`, explainWarnings: (n: number) => `${n} warnings`, explainNoWarnings: 'no warnings found',
    explainRuntime: 'Estimated run time', explainPos: 'Position afterwards', explainClear: 'Clear', explainDisclaimer: 'The explanation is a reading aid, not a check — it cannot prove that the program is safe for your machine.',
    explainKinds: { motion: 'Movement', modal: 'Setting', spindle: 'Spindle', tool: 'Tool', coolant: 'Coolant', program: 'Program flow', comment: 'Comment', empty: 'Empty', unknown: 'Unknown' } as Record<string, string>,
    // status
    cursor: 'Cursor', selected: (n: number) => `${n} selected`, unsaved: 'unsaved changes', saved: 'saved', autosaved: 'autosaved',
    // import dialog
    importTitle: 'Import drawing', importUnitUnknown: 'The file does not declare a unit. Choose the unit its coordinates are in:', importScale: 'Scale factor', importAs: 'Import as', importOneShape: 'one object', importPerLayer: 'one object per layer', importPerPath: 'one object per closed outline', importWarnings: 'Notes', ok: 'OK',
    unitMm: 'mm', unitInch: 'inch', unitCm: 'cm', unitPx: 'px (96 dpi)',
    // text
    textTitle: 'Text', textContent: 'Text', font: 'Font', fontSize: 'Height (cap height ≈ 70 %)', letterSpacing: 'Letter spacing', align: 'Alignment', aligns: { left: 'left', center: 'centre', right: 'right' } as Record<string, string>, textTool: 'Tool', textOp: 'Machining', textOps: { engrave: 'Engrave along the outline (V-bit / small tool)', pocket: 'Carve out the letters (pocket inside)', contour: 'Cut letters out (contour outside)', none: 'Only place the text' } as Record<string, string>, textCreate: 'Create text', textUpdate: 'Update text', uploadFont: 'Upload font (TTF/OTF)', minStroke: (w: string) => `Thinnest stroke ≈ ${w} mm`, toolTooBig: (d: string, w: string) => `The Ø${d} mm tool does not fit into the letter strokes (≈ ${w} mm). Use a smaller tool, a larger size or a bolder font.`, toolOk: 'Tool fits into the letter strokes.', editText: 'Edit text…',
    threadPitch: 'Pitch', threadMajor: 'Nominal diameter', threadKind: 'Thread', threadKinds: { internal: 'internal (nut)', external: 'external (bolt)' } as Record<string, string>, threadPasses: 'Radial passes', threadHint: 'Helix from the bottom upwards, one pitch per revolution; the start depth is the top of the thread.',
    // misc
    undo: 'Undo', redo: 'Redo', shortcuts: 'Keyboard shortcuts', calculator: 'Calculator',
    errors: { noMachine: 'No machine selected.', noTool: 'Operation has no tool.', postMissing: 'Post-processor profile not found.', imaUnsupported: 'The IMA BIMA exporter (IMAWOP FMC) is not implemented yet.' } as Record<string, string>,
    opNames: { contour: 'Contour', cutout: 'Cutout', pocket: 'Pocket', engrave: 'Engraving', drill: 'Drilling', thread: 'Thread', 'laser-cut': 'Laser cut', 'laser-engrave': 'Laser engraving' } as Record<string, string>,
  },
  de: {
    appTitle: 'Makerspace CAM',
    tabFile: 'Datei', tabLayout: 'Layout', tabOps: 'Bearbeitungen', tabMachine: 'Maschine', tabView: 'Ansicht',
    newProject: 'Neu', open: 'Öffnen', saveFile: 'Speichern', saveAs: 'Speichern unter…', importDrawing: 'DXF/SVG importieren', exportGcode: 'G-Code exportieren', options: 'Einstellungen', recent: 'Zuletzt',
    move: 'Verschieben', rotate90: '90° drehen', rotateCcw: '−90° drehen', mirrorX: 'Spiegeln X', mirrorY: 'Spiegeln Y', array: 'Raster', group: 'Gruppieren', ungroup: 'Gruppe auflösen', duplicate: 'Duplizieren', deleteSel: 'Löschen', addText: 'Text', addPoint: 'Bohrpunkt', zeroPoint: 'Nullpunkt', sheet: 'Platte', fit: 'Ansicht einpassen', center: 'Auf Platte zentrieren',
    contourOutside: 'Kontur außen', contourInside: 'Kontur innen', contourOn: 'Kontur auf Linie', cutout: 'Ausschnitt', pocket: 'Tasche', engrave: 'Gravur', drill: 'Bohrung', thread: 'Gewinde', laserCut: 'Laser schneiden', laserEngrave: 'Laser gravieren', activeTool: 'Aktives Werkzeug', noTool: 'kein Werkzeug', selectFirst: 'Zuerst eine oder mehrere Konturen auswählen.',
    machine: 'Maschine', postProcessor: 'Postprozessor', generate: 'G-Code erzeugen', simulate: 'Simulieren', estTime: 'Laufzeit ca.',
    grid: 'Raster', snap: 'Fangen', showMilling: 'Fräsbild', showToolpaths: 'Werkzeugwege', showRapids: 'Eilgänge', layers: 'Ebenen', view2d: '2D-Layout', view3d: '3D-Vorschau', viewGcode: 'G-Code', language: 'Sprache', darkMode: 'Dunkler Modus',
    tree: 'Projekt', tools: 'Werkzeuge', unassigned: 'Nicht zugewiesene Objekte', groups: 'Gruppen', operations: 'Bearbeitungen', objects: 'Objekte', noObjects: 'Noch keine Objekte. DXF- oder SVG-Datei importieren.', instances: (n: number) => `× ${n}`,
    params: 'Eigenschaften', nothingSelected: 'Nichts ausgewählt', placement: 'Platzierung', name: 'Name', posX: 'X', posY: 'Y', rotation: 'Drehung', scale: 'Skalierung', mirrored: 'Gespiegelt', arrayNx: 'Spalten', arrayNy: 'Zeilen', arrayDx: 'Abstand X', arrayDy: 'Abstand Y', paths: 'Pfade', closedPaths: 'geschlossen', openPaths: 'offen', size: 'Größe', layer: 'Ebene', locked: 'Gesperrt',
    stock: 'Rohteil / Platte', width: 'Breite', height: 'Höhe', thickness: 'Dicke', material: 'Material', safeZ: 'Sicherheitshöhe Z', clearZ: 'Anfahrhöhe Z', zZero: 'Z-Nullpunkt', zTop: 'Oberkante Material', zBottom: 'Maschinenbett', originMode: 'Nullpunkt', origin: { manual: 'Manuell', 'sheet-corner': 'Plattenecke', 'sheet-center': 'Plattenmitte', 'parts-bbox-corner': 'Ecke der Teile', 'parts-bbox-center': 'Mitte der Teile' } as Record<string, string>, corner: 'Ecke', corners: { bl: 'unten links', br: 'unten rechts', tl: 'oben links', tr: 'oben rechts' } as Record<string, string>,
    materials: { mdf: 'MDF', osb: 'OSB', plywood: 'Multiplex', wood: 'Massivholz', aluminium: 'Aluminium', acrylic: 'Acryl', generic: 'Allgemein' } as Record<string, string>,
    operation: 'Bearbeitung', opType: 'Art', tool: 'Werkzeug', depth: 'Tiefe', stepDown: 'Zustellung', side: 'Seite', sides: { outside: 'außen', inside: 'innen', on: 'auf der Linie', left: 'links', right: 'rechts' } as Record<string, string>, entry: 'Eintauchen', entries: { plunge: 'senkrecht', ramp: 'Rampe', helix: 'Helix' } as Record<string, string>, rampAngle: 'Rampenwinkel', climb: 'Gleichlauf', startT: 'Startposition', startAngle: 'Startwinkel', zOffset: 'Starttiefe', zOffsetHint: 'Tiefe unter der Oberfläche, an der das Fräsen beginnt (z. B. 2 nach 2 mm Planfräsen); gefräst wird von Starttiefe bis Starttiefe + Tiefe.', feedOverride: 'Vorschub (überschreiben)', plungeOverride: 'Eintauchvorschub (überschreiben)', enabled: 'Aktiv', targets: 'Ziele', tabs: 'Haltestege', tabCount: 'Anzahl', tabWidth: 'Breite', tabHeight: 'Höhe', overcut: 'Eckenfreiräumung', overcuts: { none: 'keine', dogbone: 'Hundeknochen', tbone: 'T-Knochen' } as Record<string, string>, strategy: 'Strategie', strategies: { offset: 'konturparallel', raster: 'linear (Zeilen, abheben)', zigzag: 'Zickzack (hin, zustellen, zurück)' } as Record<string, string>, rasterAngle: 'Zeilenwinkel', stepOver: 'Seitliche Zustellung', pocketSide: 'Konturgang', pocketSides: { inside: 'innerhalb der Kontur', on: 'auf der Kontur', outside: 'außerhalb der Kontur (+ Sicherheitszone)' } as Record<string, string>, outsideWidth: 'Materialabtrag um die Kontur', widthUnits: { mm: 'mm', tool: 'Werkzeugbreiten' } as Record<string, string>, outsideWidthHint: 'Materialabtrag außerhalb der Kontur (Sicherheitszone für andere Werkzeuge); die Innenfläche wird immer mit geräumt.', pocketHint: 'Zuerst der Konturgang, danach wird die gesamte Innenfläche mit der seitlichen Zustellung geräumt. Aussparungen bleiben stehen (plus Rand).', roleCut: 'Fläche (räumen)', roleExclude: 'Aussparung (bleibt stehen)', margin: 'Rand um Aussparung', addSelection: 'Ausgewählte Konturen hinzufügen', addSelectionExclude: 'Auswahl als Aussparung hinzufügen', tabMode: 'Platzierung', tabModes: { auto: 'automatisch (zuerst gegenüberliegende gerade Seiten)', manual: 'manuell (Klick in der 2D-Ansicht)' } as Record<string, string>, placeTabs: 'Stege in 2D-Ansicht platzieren', placingTabs: 'Stege platzieren… Klick auf die Kontur setzt einen Steg, Klick auf einen Steg entfernt ihn', stopPlacing: 'Fertig', tabsPlaced: (n: number) => `${n} platziert`, placePoints: 'Punkte in 2D-Ansicht setzen', placingPoints: 'Punkte setzen… Klick auf einen Fangpunkt (Linienmitte, ⅓ ⅔ ¼ ¾, Konturmitte) setzt einen Punkt, Klick auf einen Punkt entfernt ihn. Punkt kurz anvisieren = Referenz; zwei Referenzen spannen eine gepunktete Hilfslinie mit eigenen Fangpunkten auf. Esc löscht.', pointsPlaced: (n: number) => `${n} Punkte`, pointAt: (x: number, y: number) => `Punkt (${x.toFixed(2)}, ${y.toFixed(2)})`, reference: 'Referenz', snapHintTabs: 'Beim Platzieren werden Fangpunkte (Linienmitte, ⅓ ⅔ ¼ ¾) hervorgehoben.',
    depthThrough: 'durch (Dicke + 1 mm)',
    toolLibrary: 'Werkzeugbibliothek', machines: 'Maschinen', posts: 'Postprozessoren', addTool: 'Werkzeug hinzufügen', addMachine: 'Maschine hinzufügen', toolKind: 'Art', toolKinds: { endmill: 'Schaftfräser', facemill: 'Planfräser', ballnose: 'Kugelfräser', vbit: 'V-Fräser', drill: 'Bohrer', saw: 'Sägeblatt', laser: 'Laser' } as Record<string, string>, fluteLength: 'Schneidenlänge', surface: 'Planen (ganze Platte)', surfaceHint: 'Plant die ganze Platte mit dem aktiven Werkzeug ab der Starttiefe um die angegebene Tiefe.', slot: 'Werkzeugnummer (T)', diameter: 'Durchmesser', flutes: 'Schneiden', tipAngle: 'Spitzenwinkel', spindleSpeed: 'Drehzahl', feed: 'Vorschub', plungeFeed: 'Eintauchvorschub', stepOverPct: 'Seitliche Zustellung (% von Ø)', assistant: 'Schnittdaten-Assistent', applyToTool: 'Ins Werkzeug übernehmen', close: 'Schließen', save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', confirmDelete: (n: string) => `„${n}“ löschen?`, duplicateItem: 'Duplizieren',
    machineName: 'Name', machineKind: 'Typ', kinds: { cnc: 'CNC-Fräse', laser: 'Laser' } as Record<string, string>, travelX: 'Verfahrweg X', travelY: 'Verfahrweg Y', travelZ: 'Verfahrweg Z', nMax: 'Max. Drehzahl', nMin: 'Min. Drehzahl', feedMaxXy: 'Max. Vorschub XY', feedMaxZ: 'Max. Vorschub Z', rapidXy: 'Eilgang XY', rapidZ: 'Eilgang Z', toolChange: 'Werkzeugwechsel', toolChanges: { manual: 'manuell', auto: 'automatisch' } as Record<string, string>, climbAllowed: 'Gleichlauf erlaubt', climbNotAllowed: 'Auf dieser Maschine ist Gleichlauffräsen nicht erlaubt; es wird im Gegenlauf gefräst.', info: 'Notizen', importPp: 'Estlcam .pp importieren', exportPp: '.pp exportieren', builtIn: 'vorinstalliert',
    gcodeEmpty: 'Noch keine Bearbeitungen. Konturen auswählen und im Tab „Bearbeitungen“ eine Bearbeitung hinzufügen.', preparing3d: '3D-Vorschau wird vorbereitet…', building3dGrid: 'Oberflächengitter wird aufgebaut', simulating3d: (pct: number) => `Materialabtrag wird simuliert · ${pct} %`, loading3d: '3D-Vorschau wird geladen…', lines: (n: number) => `${n} Zeilen`, download: 'Herunterladen', copy: 'Kopieren', copied: 'Kopiert',
    gcodeWarnTitle: 'Eigener G-Code-Generator — Benutzung auf eigene Gefahr',
    gcodeWarnBanner: 'Dies ist ein eigener G-Code-Generator. Die Benutzung erfolgt auf eigene Gefahr — Maschine im Blick behalten und beim kleinsten Problem den Not-Aus drücken.',
    gcodeWarnLead: 'Dieses Programm ist ein eigener („custom“) G-Code-Generator. G-Code ist nicht wirklich standardisiert und keine Software ist fehlerfrei — Teile der Ausgabe wurden geprüft, eine Garantie für deine Maschine und dein Werkstück gibt es aber nicht.',
    gcodeWarnPoints: [
      'Die Benutzung des erzeugten G-Codes erfolgt vollständig auf eigene Gefahr.',
      'Programm (und 2D-/3D-Vorschau) vor dem Fahren prüfen.',
      'Die Maschine nie unbeaufsichtigt laufen lassen — immer im Blick behalten.',
      'Die Hand am Not-Aus (nicht an der Pause) halten und ihn sofort drücken, sobald etwas nicht stimmt.',
      'Im Zweifel erst über dem Material oder mit reduziertem Vorschub testen.',
    ] as string[],
    gcodeWarnAck: 'Verstanden — exportieren',
    srcProgram: 'Erzeugtes Programm', srcCustom: 'Eigener G-Code', pastePlaceholder: 'G-Code hier einfügen…', pasteEmpty: 'Oben G-Code einfügen — jede Zeile wird für die gewählte Maschine erklärt.',
    explainFor: 'Erklärt für', explainSelect: 'Zeile anklicken, um die Details zu sehen.', explainLine: (n: number) => `Zeile ${n}`, explainWarnings: (n: number) => `${n} Hinweise`, explainNoWarnings: 'keine Auffälligkeiten',
    explainRuntime: 'Geschätzte Laufzeit', explainPos: 'Position danach', explainClear: 'Leeren', explainDisclaimer: 'Die Erklärung ist eine Lesehilfe, keine Prüfung — sie kann nicht beweisen, dass das Programm für deine Maschine sicher ist.',
    explainKinds: { motion: 'Bewegung', modal: 'Einstellung', spindle: 'Spindel', tool: 'Werkzeug', coolant: 'Kühlung', program: 'Programmablauf', comment: 'Kommentar', empty: 'Leer', unknown: 'Unbekannt' } as Record<string, string>,
    cursor: 'Cursor', selected: (n: number) => `${n} ausgewählt`, unsaved: 'ungespeicherte Änderungen', saved: 'gespeichert', autosaved: 'automatisch gesichert',
    importTitle: 'Zeichnung importieren', importUnitUnknown: 'Die Datei gibt keine Einheit an. Einheit der Koordinaten wählen:', importScale: 'Skalierungsfaktor', importAs: 'Importieren als', importOneShape: 'ein Objekt', importPerLayer: 'ein Objekt pro Ebene', importPerPath: 'ein Objekt pro geschlossener Kontur', importWarnings: 'Hinweise', ok: 'OK',
    unitMm: 'mm', unitInch: 'Zoll', unitCm: 'cm', unitPx: 'px (96 dpi)',
    textTitle: 'Text', textContent: 'Text', font: 'Schrift', fontSize: 'Höhe (Großbuchstaben ≈ 70 %)', letterSpacing: 'Zeichenabstand', align: 'Ausrichtung', aligns: { left: 'links', center: 'zentriert', right: 'rechts' } as Record<string, string>, textTool: 'Werkzeug', textOp: 'Bearbeitung', textOps: { engrave: 'Gravur entlang der Kontur (V-Fräser / kleiner Fräser)', pocket: 'Buchstaben ausfräsen (Tasche innen)', contour: 'Buchstaben ausschneiden (Kontur außen)', none: 'Nur Text platzieren' } as Record<string, string>, textCreate: 'Text erstellen', textUpdate: 'Text aktualisieren', uploadFont: 'Schrift hochladen (TTF/OTF)', minStroke: (w: string) => `Dünnster Strich ≈ ${w} mm`, toolTooBig: (d: string, w: string) => `Der Ø${d}-mm-Fräser passt nicht in die Buchstabenstriche (≈ ${w} mm). Kleineres Werkzeug, größere Schrift oder fettere Schriftart wählen.`, toolOk: 'Werkzeug passt in die Buchstabenstriche.', editText: 'Text bearbeiten…',
    threadPitch: 'Steigung', threadMajor: 'Nenndurchmesser', threadKind: 'Gewinde', threadKinds: { internal: 'Innengewinde (Mutter)', external: 'Außengewinde (Bolzen)' } as Record<string, string>, threadPasses: 'Radiale Durchgänge', threadHint: 'Helix von unten nach oben, eine Steigung je Umdrehung; die Starttiefe ist die Oberkante des Gewindes.',
    undo: 'Rückgängig', redo: 'Wiederholen', shortcuts: 'Tastenkürzel', calculator: 'Rechner',
    errors: { noMachine: 'Keine Maschine ausgewählt.', noTool: 'Bearbeitung hat kein Werkzeug.', postMissing: 'Postprozessor-Profil nicht gefunden.', imaUnsupported: 'Der IMA-BIMA-Export (IMAWOP FMC) ist noch nicht implementiert.' } as Record<string, string>,
    opNames: { contour: 'Kontur', cutout: 'Ausschnitt', pocket: 'Tasche', engrave: 'Gravur', drill: 'Bohrung', thread: 'Gewinde', 'laser-cut': 'Laserschnitt', 'laser-engrave': 'Lasergravur' } as Record<string, string>,
  },
};
export type CamStrings = (typeof camStrings)['en'];
