import type { PostProfile } from '../types';
import { estlcamHolz } from './estlcam-holz';

export const grblMill: PostProfile = {
  ...estlcamHolz,
  id: 'grbl-mill', name: 'Generic GRBL mill', builtIn: true, raw: undefined,
  words: { ...estlcamHolz.words, X: { ...estlcamHolz.words.X, format: '0.###' }, Y: { ...estlcamHolz.words.Y, format: '0.###' }, Z: { ...estlcamHolz.words.Z, format: '0.###' }, I: { ...estlcamHolz.words.I, format: '0.###' }, J: { ...estlcamHolz.words.J, format: '0.###' } },
  cmds: { rapid: 'G0', linear: 'G1', cw: 'G2', ccw: 'G3' },
  blocks: {
    ...estlcamHolz.blocks,
    programStart: '(Project <project>)\n(Generated by Makerspace CAM <version>, ~<time>)\nG21 G90 G17 G94\n(Tool T<t>: <n>)\nM3 S<s>\nG4 P2',
    toolChange: 'M5\nM0 (Change tool to T<t>: <n>)\nM3 S<s>\nG4 P2',
    programEnd: 'M5\nM30',
    dwell: 'G4 P<seconds>',
  },
};

export const grblLaser: PostProfile = {
  ...grblMill,
  id: 'grbl-laser', name: 'Generic GRBL laser (M4 dynamic power)', builtIn: true,
  words: { ...grblMill.words, Z: { ...grblMill.words.Z, enable: false }, S: { ...grblMill.words.S, repeat: false } },
  blocks: {
    ...grblMill.blocks,
    programStart: '(Project <project>)\n(Generated by Makerspace CAM <version>, ~<time>)\nG21 G90 G17 G94\n<mode> S0',
    toolChange: '',
    programEnd: 'M5\nG0 X0 Y0\nM30',
    laserOn: '<mode> S<s>', laserOff: 'M5',
  },
};
